version: "3"

services:
  react-test:
    build:
      # the root directory
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

  react-app:
    build:
      # the root directory
      context: .
      dockerfile: Dockerfile.dev
    depends_on: react-test
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app


